name: Update RSS Feed HTML

on:
  schedule:
    - cron: '0,30 * * * *'

permissions:
  contents: write
    
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run RSS Feeder
        run: python rss_feeder.py

      - name: Configure Git
        run: 
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit changes
        run: |
          git add index.html
          git commit -m "Daily RSS Update" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
           # Re-point origin to use the GITHUB_TOKEN
           git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/JWT890/rss-python-feeder2.git
           git push origin main

