name: Update RSS Feed HTML

on:
  schedule:
    - cron: '0,30 * * * *'
    
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run RSS Feeder
        run: python rss_feeder.py

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions"@github.com"
          git add index.html
          git commit -m "Daily RSS Update" || echo "No changes to commit"
          git push
