name: Update RSS Feed HTML

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0,30 * * * *'

permissions:
  contents: write
  pages: write
  id-token: write
    
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persistent-credentials: false
      
      - name: Debug Check
        run: echo "Github Actions workflow started"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run RSS Feeder
        run: python rss_feeder.py

      - name: Configure Git
        run: | 
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
        shell: bash

      - name: Commit changes
        run: |
          git add index.html
          git commit -m "Daily RSS Update" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.RSS_FEEDER_GITHUB_TOKEN }}
        run: |
           # Re-point origin to use the GITHUB_TOKEN
           git remote set-url origin https://x-access-token:${{ secrets.RSS_FEEDER_GITHUB_TOKEN }}@github.com/JWT890/rss-python-feeder2.git
           git push origin main

      - name: Upload artifact for GitHub pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    needs: update
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with: 
          github_token: ${{ secrets.RSS_FEEDER_GITHUB_TOKEN }}
          target_branch: main


